### ISSUE TITLE
Adding namespace permissions for create/delete

### ISSUE THREAD

**Issue by pierrotsmnrd** [conda-incubator/conda-store#180]
The goal of this issue is to discuss the various aspects and features of the namespaces.

Two options for their creation : 
- either they are created automatically, prepended with the username's by default, when creating an env
- or all the envs go under a global namespace by default

Also : The creation would be allowed for all the users, only the deletion would be made possible for admins

ping @costrouc @dharhas

**Comment by costrouc** [comment]
Looks like I lost the comment. I would like to create two permissions:
 - `NAMESPACE::CREATE`
 - `NAMESPACE::DELETE`

These permissions exist on the `admin` role (not developer or viewer).
