### ISSUE TITLE
Idea of forking an environment and layering on top of an environment

### ISSUE THREAD

**Issue by costrouc** [conda-incubator/conda-store#20]

**Comment by dcharbon** [comment]
Ooh, this is a great idea! I've seen this done in a python development environment before and it can be really powerful. This is very exciting!

**Comment by costrouc** [comment]
@dcharbon yeah it came up in a call with a customer today looking to use conda-store. Looking the for the most `conda` compatible way of exposing layering. Likely exposing an environment as a "metapackage" in conda-store would enable layering. Forking would be much easier to implement.

**Comment by majidaldo** [comment]
I've thoroughly explored this idea (and have code for it). It leads to something like `conda build` but for environments. The main functionality comes from conda-devenv.

**Comment by majidaldo** [comment]
As I see it as a general gap in tooling, it should be broader community issue (and not for conda-store to solve).

**Comment by costrouc** [comment]
To give more information on why I think this may be required within conda-store. Some of our clients would like the ability to enforce that for all/specific environments they contain certain packages that are pinned to a specific version. E.g. they have a base data science environment. However sometime in the future the IT team decides that all data science environments must update to the latest numpy version. We need some way to force the environments that were forked from the data science environment to update as well.

I guess the same could be achieved by a metapackage. I think this slightly different forking since we'd like the environment to always track a base environment.

**Comment by majidaldo** [comment]
> To give more information on why I think this may be required within conda-store. Some of our clients would like the ability to enforce that for all/specific environments they contain certain packages that are pinned to a specific version. E.g. they have a base data science environment. However sometime in the future the IT team decides that all data science environments must update to the latest numpy version. We need some way to force the environments that were forked from the data science environment to update as well.
> 
> I guess the same could be achieved by a metapackage. I think this slightly different forking since we'd like the environment to always track a base environment.

https://github.com/pnnl/hydraconda/tree/master

**Comment by kcpevey** [comment]
@costrouc this issue is rather old, is this still something worth considering?

**Comment by trallard** [comment]
This issue seems stale will close and if needed we can re open
