### ISSUE TITLE
Token based authentication for jupyterlab users in Conda-Store

### ISSUE THREAD

**Issue by costrouc** [conda-incubator/conda-store#213]
Right now there is no easy for a user to authenticate from jupyterlab launched via jupyterhub transparently. Currently there is a workaround to allow the gator extension to modify create/update/delete environments. 

```
c.RBACAuthorizationBackend.unauthenticated_role_bindings = {
    '*/*': ['admin'],
}
```

This makes it so that the REST api/UI effectively considers anyone(unauthenticated) to be an admin.

In order to properly handle this we must accept a jupyterhub token from the jupyterlab gator extension and get the credentials for the user based on this. Possibly this means we should expose a token based authentication method for Conda-Store.

**Comment by trallard** [comment]
Is this still applicable @costrouc?

**Comment by costrouc** [comment]
@trallard this issue is resolved as conda-store does have token based authentication and it is possible to generate new tokens.
