### ISSUE TITLE
More robust handling of failed builds and interupted workers

### ISSUE THREAD

**Issue by costrouc** [conda-incubator/conda-store#296]
Using the `acks_late` feature in celery https://docs.celeryq.dev/en/stable/userguide/tasks.html#Task.acks_late

Using an on_failure method for tasks https://stackoverflow.com/questions/21056428/can-i-add-an-on-failure-callback-to-a-celery-task-created-with-the-task-decorato.

**Comment by kcpevey** [comment]
Related:
#170 
#55

**Comment by costrouc** [comment]
https://github.com/conda-incubator/conda-store/pull/530 was aimed at cleaning up builds that are stuck in the BUILDING state. I think this should solve this issue. I'm going to close this for now and revisit if the issue persists.
