### ISSUE TITLE
Issue when building environments "channel ... not recognized in database"

### ISSUE THREAD

**Issue by costrouc** [conda-incubator/conda-store#299]
![image](https://user-images.githubusercontent.com/1740337/167033213-01065131-b73b-4556-8b6d-88f1d5370136.png)

**Comment by pierrotsmnrd** [comment]
What is the expected behavior ? 
Is the build supposed to fail, but catching the exception ? 
Or should the channel be added in the database ?

**Comment by peytondmurray** [comment]
Going to add a little more info here, as this has become a blocking issue for me:

```yaml
dependencies:
- hvplot
- pip
- pip:
  - tqdm @ git+https://github.com/tqdm/tqdm@master
name: test-environment
```

Fails to build, but it seems like it only fails at the end of the build:

```
Traceback (most recent call last):
  File "/opt/conda-store-server/conda_store_server/build.py", line 179, in build_conda_environment
    set_build_completed(conda_store, build, output.encode("utf-8"), packages)
  File "/opt/conda-store-server/conda_store_server/build.py", line 45, in set_build_completed
    raise ValueError(
ValueError: channel url=https://repo.anaconda.com/pkgs/main not recognized in conda-store channel database
```

**Comment by kcpevey** [comment]
Related: https://github.com/Quansight/conda-store/issues/275

**Comment by trallard** [comment]
@steff456 @pierrotsmnrd  Now that we have removed the restrictions on channels via #545 can you both please have a look at this issue and


1. lmk if this is still an issue
2. if so, discuss and work on a fix? if not, then we can close this issue

**Comment by steff456** [comment]
I've tested the original environment in the current `main` branch and it is working without the need of adding the `main` channel.

```
channels:
  - conda-forge
dependencies:
  - hvplot
  - pip
  - pip:
      - tqdm @ git+https://github.com/tqdm/tqdm@master
  - ipykernel
```

I think this issue was resolved 🎉
