### ISSUE TITLE
Ability to cancel a build.

### ISSUE THREAD

**Issue by dharhas** [conda-incubator/conda-store#306]
I made a mistake in my YAML spec and realized I needed to add some more packages. There is no way to stop a long running build.

**Comment by costrouc** [comment]
This looks possible https://stackoverflow.com/questions/8920643/cancel-an-already-executing-task-with-celery

**Comment by costrouc** [comment]
Linking https://github.com/conda-incubator/conda-store/pull/531. There is no progress to report from @nkaretnikov

**Comment by nkaretnikov** [comment]
Related, but can be done separately: https://github.com/conda-incubator/conda-store/issues/547

**Comment by nkaretnikov** [comment]
Status update:
- Reviewed the linked PR. It's almost ready.
- Still need to make changes, but I currently have no dedicated hours for this. Might happen during unallocated hours this week or in 1 week.

**Comment by nkaretnikov** [comment]
Status update: this should be fixed by #531, it's in review.
