### ISSUE TITLE
Editing YAML spec doesn't change YAML display until build is complete.

### ISSUE THREAD

**Issue by dharhas** [conda-incubator/conda-store#307]
1. I edited a YAML file and clicked save and a build started. 
2. I realized I had missed some packages. There is no way to cancel a build ( See #306 )
3. I decided to click edit again and add the missing package.
4. After both builds had completed I realized that my latest build was missing packages I wanted since I had edited the original spec and not the modified spec I created in 1.

Essentially after you hit build the spec doesn't change. I sorta understand why i.e. the new spec hasn't built yet. But this makes it easy to make mistakes.

My suggestion. Lock the spec while the env is building and provide a cancel build button.

**Comment by trallard** [comment]
@kcpevey - is this still the current behaviour? - the cancelling step is being worked on atm

**Comment by kcpevey** [comment]
As mentioned above, the ability to cancel a build is now a separate issue. As for the yaml spec, this incorrect behavior is no longer happening. 

We now have a dropdown menu to specify which environment we are currently viewing. Selecting a different environment in this menu properly switches the view/non-edit screen, the ui-edit screen, and the yaml-edit screen.
