### ISSUE TITLE
Develop helm chart for conda-store and public to chartpress

### ISSUE THREAD

**Issue by costrouc** [conda-incubator/conda-store#360]
Links:
 - chartpress https://github.com/jupyterhub/chartpress

Would like to follow the same pattern that dask-gateway took:
 - https://github.com/dask/dask-gateway/tree/main/resources
 - https://github.com/dask/dask-gateway/blob/main/.github/workflows/build-publish-helm-chart.yaml

This would create an official helm chart for conda-store. This will allow qhub to decouple from conda-store more.

**Comment by trallard** [comment]
@costrouc  is this still applicable?

**Comment by costrouc** [comment]
Long term this should be created. We need an easy way to deploy conda-store on Kubernetes and this would help nebari so that we don't need to maintain a terraform module for conda-store there.

But I think this is worth closing until we have a need.
