### ISSUE TITLE
Create community & governance documentation

### ISSUE THREAD

**Issue by pavithraes** [conda-incubator/conda-store#399]
Document infrastructure, project management, and maintenance workflows.

For reference: https://github.com/conda-incubator/governance & https://www.nebari.dev/docs/community

- [x] Introduction (support, governance, etc.)
- [x] Contribute - Code (Development setup)
- [x] Contribute - Documentation
- [x] Contribute - Docs Style Guide
- [x] Contribute - Testing workflows
- [x] Maintenance - Triage guidelines
- [x] Maintenance - GitHub conventions
- [x] Maintenance - Saved replies
- [x] Maintenance - Release process
- [x] Policy: #595
- [x] #679

**Comment by costrouc** [comment]
@pavithraes is there an update on this?

**Comment by pavithraes** [comment]
@costrouc - I'm back on the conda-store project this week, and will pick it back up. :)
