### ISSUE TITLE
Update current docs to use the new UI 

### ISSUE THREAD

**Issue by pavithraes** [conda-incubator/conda-store#400]
The conda-store docs still contain screenshots of the previous UI; the docs need to be updated to ensure alignment with the status of the UI. 

```[tasklist]
### Tasks
- [ ] Investigate is we could use Playwright to automate the screenshot generation (similar to JupyterLab)
- [ ] Based on the results from above, automate screenshots through Playwright and GH actions
``` 

## References 🔗 

New conda-store UI: https://github.com/Quansight/conda-store-ui
Playwright docs: https://playwright.dev/python/docs/intro

**Comment by trallard** [comment]
Is this still needed @pavithraes

**Comment by pavithraes** [comment]
Yes, this is still needed

**Comment by kcpevey** [comment]
Very much needed!

**Comment by costrouc** [comment]
The docs in this area need a general rewrite. Also note that many of the features in the old UI are not available in conda-store ui. Not sure how to address this issue in the docs.

**Comment by pavithraes** [comment]
This work is now being tracked in #570 - closing as duplicate. :)
