### ISSUE TITLE
Changing environment name in yaml creates a new environment.

### ISSUE THREAD

**Issue by dharhas** [conda-incubator/conda-store#416]
This is not a bug per se, but is slightly surprising and needs documentation. Changing the environment name in the yaml editor creates a new environment. Thinking through it, from a reproducibility pov this might be the right thing to do, but it was a bit surprising. I think we at least need to document this, but also have a discussion on what the right behaviour should be.

**Comment by anirrudh** [comment]
I don't think we should let users change an environment name and instead enforce cloning the environment. Looking at older issues such as #290 , I feel like it would be easier to control the env "version" number scope as well. This begs the question: "What is the motivation for changing the name?"

When I manage my own environments, I just export an environment.yaml and change the attributes if I'm making a new environment anyway, including the name, or I use the builtin env clone command. I hope to hear how others think about this problem!

**Comment by kcpevey** [comment]
This no longer valid. Changing the environment name is no longer allowed.
