### ISSUE TITLE
Enable Papermill to work without requiring work around

### ISSUE THREAD

**Issue by Adam-D-Lewis** [conda-incubator/conda-store#436]
If I create a papermill environment
```
channels:
- conda-forge
dependencies:
- python
- papermill
- pyarrow
- pandas
- ipykernel
description: ''
name: papermill
prefix: null
```
and a nebari-git-dask environment
```
channels:
- conda-forge
dependencies:
- python
- ipykernel
- ipywidgets==7.7.1
- nebari-dask ==2023.1.1
- python-graphviz
- pyarrow
- s3fs
- gcsfs
- numpy
- numba
- pandas
- pip:
  - kbatch
description: ''
name: dask
prefix: null
```

and then try to run papermill via `papermill cron-notebook.ipynb cron-notebook-results.ipynb` it will fail with `jupyter_client.kernelspec.NoSuchKernel: No such kernel named conda-env-nebari-git-nebari-git-dask-py`. 

A workaround can be done with:
- `conda activate nebari-git-dask`
- `python -m ipykernel install --user --name myenv --display-name "Python (myenv)"`
- ` conda activate papermill`

after which `papermill -k myenv cron-notebook.ipynb cron-notebook-results.ipynb` will then run as intended.

Is there something that could be done to avoid having to perform this manual step to get papermill to work?

**Comment by Adam-D-Lewis** [comment]
Including some slack conversation in case useful in the future
![image](https://user-images.githubusercontent.com/23342526/227968066-aa68e075-f083-4c2d-ac3e-60fbb40a2735.png)

**Comment by trallard** [comment]
Is this still applicable @costrouc?

**Comment by trallard** [comment]
I have not heard back, so I will assume this is not applicable and we do not have enough information to triage. 

If needed, we can re-open the issue.

**Comment by costrouc** [comment]
@trallard yes I would say that this is out of the scope of conda-store. I'd like to minimize the modifications that we make to environments and rely soley on conda/mamba/micromamba/pip etc.
