### ISSUE TITLE
Docker link uses localhost domain

### ISSUE THREAD

**Issue by Adam-D-Lewis** [conda-incubator/conda-store#437]
Clicking the Docker link gives a localhost url. e.g. for the dashboard environment localhost:5000/nebari-git/dashboard:8779853fe3b0502c53abbdb7b7b7d1dfc1c09847777073ee2d67fefbd6c6f855-20230130-182156-597614-35-dashboard.

It'd be nice if localhost was at least able to be configured to something else.  Note I'm running conda-store as part of Nebari.

**Comment by costrouc** [comment]
Thanks for the issue @Adam-D-Lewis . I'm thinking this has to do with not setting the domain properly. There should be enough information in being able to get the external domain. This should be a relatively easy fix.

**Comment by Adam-D-Lewis** [comment]
I believe Docker is no longer supported so I'll close this issue.
