### ISSUE TITLE
Using conda-lock and parallel builds

### ISSUE THREAD

**Issue by costrouc** [conda-incubator/conda-store#470]
Currently builds are failing for the following environment

```yaml
pytorch
pandas
ipykernel
```

Also conda-lock is not working if the current direction is not writable. We need to add some logic around that.

**Comment by trallard** [comment]
@costrouc  is this still applicable? Also the title and the content of the issue somehow do not match, is there any information missing?

**Comment by costrouc** [comment]
Yeah this is worth closing. This was an issue I was having with a client on a newer version of conda-store. No longer applicable and we do have parallel builds now.
