### ISSUE TITLE
Add environment creator to metadata

### ISSUE THREAD

**Issue by kcpevey** [conda-incubator/conda-store#489]
## Background

Over time, environments tend to accumulate. On our personal machines, its easy to clean out old envs that we know we dont need anymore. On conda-store, its very challenging to clean out old envs because we don't know who they "belong" to or if they are still being used. 

## Desired behaviour

Adding the username or email address of the creator and who made each update into the environment metadata (and then displaying it in the UI) would be extremely helpful with platform management of environments.

**Comment by trallard** [comment]
This seems to be addressed by the recent addition of querying envs based on namespace/user. 
 So will close.
