### ISSUE TITLE
logout method does not clear subdomain cookie

### ISSUE THREAD

**Issue by costrouc** [conda-incubator/conda-store#512]
Currently when a user logs out when `Authentication.cookie_domain` is set. The cookie is not properly deleted.

To fix the https://github.com/conda-incubator/conda-store/blob/b9063dd003e04b892b6fb0c57c6e31bd4e773f62/conda-store-server/conda_store_server/server/auth.py#L452 the `domain` key needs to be set.

**Comment by anirrudh** [comment]
@costrouc I need some more information on this issue, I'm not entirely sure what you had in mind here. What is the domain key and where does it need to be set?

**Comment by costrouc** [comment]
The set_cookie method is provided by starlette under the covers via https://github.com/encode/starlette/blob/a8b8856ce393a82ab4a714131085dbc4d658e34d/starlette/responses.py#L86-L97.

This is the code that should be there instead

`response.set_cookie(self.cookie_name, "", domain="", expires=0)`
