### ISSUE TITLE
Improve pydantic validation check error reporting on yaml specification

### ISSUE THREAD

**Issue by kcpevey** [conda-incubator/conda-store#535]
### Describe the issue

I have a conda yaml that passes a yaml linter for valid yaml spec, but when I try to use conda-store-ui to create an env with it, I get an error about validation. 

```
channels:
  - conda-forge
  - pytorch
dependencies:
  - python >= 3.8
  - typing-extensions >= 4.5,!= 4.6
  - numpy >= 1.17

  - pillow >= 9.4.0
  - pytorch >= 1.7,!=1.12.0
  - torchvision >= 0.14.1
  - datasets >= 2.7.1
  - transformers >= 4.25.1
  - timm >= 0.6.12
  - torchmetrics >= 0.11,< 1.0
  - tqdm >= 4.62.1

  - # test
  - jupytext >= 1.14.0
  - numpydoc >= 1.5.0
  - pyright >= 1.1.280
  - pytest >= 7.0.0
  - hypothesis >= 6.61.0
  - pytest-mock >= 3.10.0

  - pip:
      - huggingface-hub >= 0.11.1
      - torcheval >= 0.0.6
```

The error is:
```
1 validation error for CondaSpecification dependencies -> 11 none is not an allowed value (type=type_error.none.not_allowed)
```

### Expected behavior

I expect conda-store to give me an explanation of the validation error - 
* What part of my yaml spec failed?
* What line number (of my original spec) failed?
* Or was it something in the description that failed?

### How to Reproduce the problem?

Copy and paste the above into a new environment yaml spec on nebari conda store ui. 

### Output

![image](https://github.com/conda-incubator/conda-store/assets/15659110/b67c7967-c329-4e0c-9664-49365bd56221)

```[tasklist]
### Tasks
- [ ] Pydantic schema - Identify improvements needed
- [ ] Improve thrown error message from PyDantic validation
```

**Comment by kcpevey** [comment]
Its not a bug... I did a find/replace and `- # test` is not an acceptable package. So this issue is just a need to explain what failed the validation check.

**Comment by costrouc** [comment]
@kcpevey I was just checking out this bug that you mentioned and ran into the same issue you had and the error obviously was not helpful.

Right now I am relying on pydantics error messages which are obviously not helpful here. We need to figure out how to update the pydantic models in the schema to give better error messages. Additionally I think this issue would have been a lot easier to debug if we had a better indication of the location of the error.

**Comment by costrouc** [comment]
There is a single place where this validation logic can be parsed and displayed to the user better.

https://github.com/conda-incubator/conda-store/blame/main/conda-store-server/conda_store_server/server/views/api.py#L567-L568
