### ISSUE TITLE
[BUG] - conda-lock lockfile is not backwards compatible needs to be fixed

### ISSUE THREAD

**Issue by costrouc** [conda-incubator/conda-store#544]
### Describe the bug

When performing an upgrade from an older conda-store to the eventual new version of conda-store we switched from generating a lockfile from the packages we knew existed in the environment to using an explicit lockfile generated by conda-lock.

In this process the BuildArtifact for each environment lockfile changed from:
  - https://github.com/conda-incubator/conda-store/blob/v0.4.15/conda-store-server/conda_store_server/build.py#L127-L129
  - https://github.com/conda-incubator/conda-store/blob/23999b9b32ec463761bfc749f2076630a2cd4396/conda-store-server/conda_store_server/build.py#L141-L148

And the method for serving the lockfile in the api changed as well:
 - https://github.com/conda-incubator/conda-store/blob/v0.4.15/conda-store-server/conda_store_server/server/views/api.py#L813
 - https://github.com/conda-incubator/conda-store/blob/23999b9b32ec463761bfc749f2076630a2cd4396/conda-store-server/conda_store_server/server/views/api.py#L907

Within the api that serves lockfile we should check if the buildartifact for LOCKFILE key is the empty string. If it is we should serve the old lockfile (that is autogenerated) otherwise we server new generated lockfile.

The bug occurs when we encouter an old environment and the key is `""` which does not point to a particular file.

### Expected behavior

Old and new environments should produce lockfiles

### How to Reproduce the problem?

Migrate from an older conda-store to the newer version.

**Comment by kcpevey** [comment]
@costrouc can you provide more context on this issue?

**Comment by costrouc** [comment]
Added details above @kcpevey

**Comment by costrouc** [comment]
I think the course of action to fix this is adding a conditional if statement in the api get lockfile function. If the BuildArtifact key for the lockfile artifact is the empty string then fallback to the method https://github.com/conda-incubator/conda-store/blob/4d23d1aa22f58f7c51040251e64a055075ba5dfe/conda-store-server/conda_store_server/api.py#L219. 

What would be really nice is that instead of returning the old `@EXPLICIT` text file you instead return a conda-lock valid file see:
 - https://github.com/conda/conda-lock/blob/main/example/pangeo/conda-lock.yml
 - https://github.com/conda/conda-lock/blob/main/conda_lock/models/lock_spec.py

Returning a valid conda-lock.yml file would be a great enhancement to this bug that was introduced. I would prefer that this be part of the PR.

**Comment by nkaretnikov** [comment]
Started working on this.
