### ISSUE TITLE
[ENH] - Sync issue/PR templates across repos 

### ISSUE THREAD

**Issue by pavithraes** [conda-incubator/conda-store#556]
### Feature description

We have 3 separate repos for conda-store development, it'll be nice to have a single source of truth for community health files like issue/pr templates, licence, etc.

Ref: https://github.com/conda-incubator/conda-store/pull/555#issuecomment-1699042036

### Value and/or benefit

Automates the process of keeping all files up to date, saves time

**Comment by trallard** [comment]
I am afraid we cannot leverage the `.github` repo approach like @asmeurer mentioned, so this will have to remain a manual process
