### ISSUE TITLE
[BUG] - Delete environment does not change storage size

### ISSUE THREAD

**Issue by kcpevey** [conda-incubator/conda-store#560]
### Describe the bug

When we go through the delete env process, we see the process "succeed", but the total storage size does not change. 

```
[2023-09-05 21:11:10,476: INFO/MainProcess] Task task_delete_build[d12572cf-694d-4341-86ab-34a21dac779f] received
[2023-09-05 21:11:10,482: WARNING/ForkPoolWorker-2] [CondaStoreWorker] deleting artifacts for build=89
[2023-09-05 21:11:13,712: INFO/ForkPoolWorker-2] Task task_delete_build[d12572cf-694d-4341-86ab-34a21dac779f] succeeded in 3.235292388126254s: None
```

We're seeing this on JATIC and @sblair-metrostar has seen this on Onyx. 

### Expected behavior

I expect when I go through the deletion process on the UI or otherwise, for the process to remove the environment from disk completely.

### How to Reproduce the problem?

* Create a big environment
* note the total storage size (via the admin interface)
* Delete the environment
* Wait a big for the deletion process to complete
* note the total storage size hasn't changed. 

I'm sure there is a better method for those with a local dev deployment of conda-store. This is just from the UI. 

### Anything else?

Related: https://github.com/conda-incubator/conda-store/issues/420

**Comment by nkaretnikov** [comment]
I got confused by this at first, so to clarify: when the issue talks about "deleting the environment" above, it means "delete the build".

**Comment by nkaretnikov** [comment]
Fixed in https://github.com/conda-incubator/conda-store/pull/572
