### ISSUE TITLE
[DOC] Document deletion options

### ISSUE THREAD

**Issue by kcpevey** [conda-incubator/conda-store#563]
### Context

If I go through the conda-store-ui, 

* go to an env
* click "Edit"
* click "Delete environment"
* All builds will be deleted. 

If I go through the conda-store/admin interface, I have the option to delete individual builds. 

This is an important distinction since we might want to remove old build versions to free up storage space. 

### Value and/or benefit

Admins and users can better understand how to maintain optimal storage.

**Comment by trallard** [comment]
@pavithraes was this ever documented?

**Comment by pavithraes** [comment]
Yes: https://conda.store/conda-store-ui/tutorials/edit-delete-envs#delete-environments

Closing as complete :)
