### ISSUE TITLE
[DOC] Add Playwright tests to grab relevant screenshots

### ISSUE THREAD

**Issue by pavithraes** [conda-incubator/conda-store#570]
Also, make sure we have descriptive image names

**Comment by kcpevey** [comment]
I'll organize the images into the directory structure {conda-store/conda-store-ui}/{diataxis section}/{descriptive filename}

**Comment by kcpevey** [comment]
playwright already exists and has a very basic integration test. 

The playwright tests for the ui exist on the conda-store repo. This has some implications:

* The way that the conda-store tests are set up, it will pull the latest release of conda-store-ui to test on. Which means that the screen shots will not be updated until conda-store-ui has a release, and the release number has been bumped in the conda-store repo as well. 
* There are no integration tests for conda-store-ui main or PRs. We are only aware of a failure once its been released and integrated at the conda-store level.

**Comment by kcpevey** [comment]
The playwright test setup has been merged. This is now unblocked. 

Where should the screenshots be stored? The documentation is in conda-store repo, but these images will be generated on the conda-store-ui repo. The easiest option is just to save them as artifacts and manually push them to the docs repo.

**Comment by costrouc** [comment]
Just noting here that the playwright test is flaky @dcmcand will open an issue.

**Comment by pavithraes** [comment]
Update - The flaky test is fixed, ref: https://github.com/conda-incubator/conda-store-ui/issues/326, https://github.com/conda-incubator/conda-store-ui/pull/321

**Comment by kcpevey** [comment]
* the workflow should be triggered manually or by commenting  `/regenerate images` or something
* the workflow to generate the images should happen on the ui repo and store images as artifacts. 
* The workflow will trigger opening a PR on the code repo

**Comment by kcpevey** [comment]
Still working on this. I had to create some test repos as a playground because some of the action triggers only work on main and I don't want to debug in the main repos. 

I looked at the `issue_comment` trigger which is what we'd need to be able to run the "push to conda-store as PR" workflow. GH doesn't have a more tightly scoped `pr_comment` trigger, which means that EVERY comment on EVERY issue and PR in this repo will trigger this workflow. I believe that's a lot of wasted compute even if the job is "if pr event", its still spinning up machines. For that reason, my plan is a manual trigger or a trigger by label.

**Comment by kcpevey** [comment]
>This does not seem right

I did code it that way, but then when I was reading the docs I guess I just misunderstood it so I reverted. I can switch it back to triggering on `issue_comment`. 

The issue will still remain that the playwright test workflow will have to have already completed before this new workflow can be triggered. I couldn't find a way around that, but if you have a suggestion there, I'm all ears!

**Comment by trallard** [comment]
This has been open for so long and @gabalafou has already raised concerns about longer term toil and maintenance for this feature (with which I agree). 

I am tempted to close this issue and the associated PR soon unless I hear compelling arguments against it and a mitigation plan for the maintenance burden and potential disruption to contribution workflows.

**Comment by soapy1** [comment]
>I am tempted to close this issue and the associated PR soon unless I hear compelling arguments against it and a mitigation plan for the maintenance burden and potential disruption to contribution workflows.

+1 to closing the issue
