### ISSUE TITLE
[BUG] - Selecting some packages when creating an env reloads the page

### ISSUE THREAD

**Issue by nkaretnikov** [conda-incubator/conda-store#575]
### Describe the bug

- open the new green UI at /
- click on + to create environment
- +Add package -> type “anaconda”
- Page reloads

Repros every time.

I think I've seen this with some other packages as well.

### Expected behavior

Package is added.
OR: if this package causes problems, it shouldn't be listed.

### How to Reproduce the problem?

See above.

### Versions and dependencies used.

229f3ac1e56d6dce5890dffebc9c2d0c26dacabf

**Comment by pavithraes** [comment]
Just to note, I couldn't reproduce this on the conda-store running on `nebari.quansight.dev`. I'm not certain what versions are currently being used there.
