### ISSUE TITLE
[BUG] - Can't install conda-store-server on M1 MacOS

### ISSUE THREAD

**Issue by ibdafna** [conda-incubator/conda-store#578]
### Describe the bug

Running the installation command results in the following:

```bash
~/dev/research
➜ m create -n env-research -c main -c conda-forge "conda-store-server>=0.4.10"
conda-forge/osx-arm64                                       Using cache
conda-forge/noarch                                          Using cache
main/noarch                                                   No change
main/osx-arm64                                                No change
error    libmamba Could not solve for environment specs
    The following package could not be installed
    └─ conda-store-server >=0.4.10  is not installable because it requires
       └─ conda-docker, which requires
          └─ fakechroot, which does not exist (perhaps a missing channel).
critical libmamba Could not solve for environment specs
```

I'm using `micromamba` here but the same issue also manifests when attempting installation via `conda`.

### Expected behavior

I'd expect the package to install.

### How to Reproduce the problem?

Run `conda create -n env-research -c main -c conda-forge "conda-store-server>=0.4.10"` in a terminal running on an M1 Mac.

### Output

See above.

### Versions and dependencies used.

```bash
~/dev/research took 32.5s
➜ conda --version
conda 23.7.4

~/dev/research
➜ m --version
1.5.0
```

### Anything else?

Many thanks for building this tool and supporting the community!

**Comment by dharhas** [comment]
Tagging @asmeurer 

@ibdafna the current release version of conda-store doesn't support OSX or Windows. @asmeurer is working on OS X and Windows compatibility. I think the plan is that it will be in the next release.

Aaron, can you update on how far along we are in that respect.

**Comment by ibdafna** [comment]
@trallard @dharhas Thank you both for the quick reply and solution.
