### ISSUE TITLE
[BUG] - `developer` role can't create envs in namesapces

### ISSUE THREAD

**Issue by pavithraes** [conda-incubator/conda-store#582]
### Describe the bug

Related to a conda-store bug we’re experiencing on Nebari: https://github.com/nebari-dev/nebari/issues/1898

### Background

At first we thought there was an issue with the logic found in the `conda_store_config.py::KeycloakAuthenticator` object here: [link to codebase](https://github.com/nebari-dev/nebari/blob/61326583141a88196dcebd7ea6005a58f3ac91de/src/_nebari/stages/kubernetes_services/template/modules/kubernetes/services/conda-store/config/conda_store_config.py#L117)

After some investigating, the permissions seem to be set correctly; if you’re a “developer”, you should get these permissions:

https://github.com/conda-incubator/conda-store/blob/432eaa11ef349fdb848215113caea22b09a23a32/conda-store-server/conda_store_server/server/auth.py#L67-L74

Questions:

1. The “developer” role in conda-store has 1NAMESPACE_READ1 permissions but I’m wondering if they might also need a few other permissions that the admin has here to be able to create/edit envs in namespaces:

https://github.com/conda-incubator/conda-store/blob/432eaa11ef349fdb848215113caea22b09a23a32/conda-store-server/conda_store_server/server/auth.py#L76C1-L89C51

2. Given that a user with the “developer” role can view all of the “namespaces”, but the button to add an environment is greyed out, it is possible that this is more of an issue with the conda-store-ui than it is with the actual permissions themselves?

---

_Originally posted by @iameskild on Slack_

cc @iameskild and and @fangchenli

### Expected behavior

Users with the `developer` role should be able to create and edit environments in the namespaces they are a part of, i.e., the `developer` namespace in the deafult case.

### How to Reproduce the problem?

1. Log-in to a Nebari instance and make sure you have the `developer` role.
2. Navigate to the conda-store-ui on Nebari -- the plus button next to the `developer` namespace will be greyed out indicating you don't have permissions to create/edit envs.

### Anything else?

Move this issue to the `conda-store-ui` repo after investigation if needed.
Remove the `block-release` label if deemed lower priority.

**Comment by pavithraes** [comment]
From @trallard -- xref: https://github.com/conda-incubator/conda-store/issues/491

**Comment by fangchenli** [comment]
I did some digging in the ui code. The line of code that directly related to env creation is [here](https://github.com/conda-incubator/conda-store-ui/blob/870957a852c7f48118f8392ea42714b09838caa0/src/features/environments/components/EnvironmentDropdown.tsx#L54).

And the corresponding variable `canCreate` got traced back to [here](https://github.com/conda-incubator/conda-store-ui/blob/870957a852c7f48118f8392ea42714b09838caa0/src/utils/helpers/namespaces.ts#L146-L148). I copied the entire function for reference. 

```typescript
export const namespacesPermissionsMapper = (
  namespaces: Namespace[],
  permissions: any
) => {
  return namespaces.map((namespace: Namespace) => {
    const entity = `${namespace.name}/*`;
    const allPermissions = permissions.data.entity_permissions["*/*"];
    const namespacePermissions =
      permissions.data.entity_permissions[entity] ?? [];

    return {
      id: namespace.id,
      name: namespace.name,
      canCreate: allPermissions
        ? true
        : namespacePermissions.includes(PERMISSIONS.namespaceCreate),
      canUpdate: allPermissions
        ? true
        : namespacePermissions.includes(PERMISSIONS.environmentUpdate)
    };
  });
};
```

Only superadmin and users with `namespaceCreate` permission are able to create env. And `developer` doesn't have this permission. We could give `developer` the `NAMESPACE_CREATE` permission in conda-store, or change the ui code.

**Comment by kcpevey** [comment]
Is this still an issue after the changes to role mapping?

**Comment by pavithraes** [comment]
> Is this still an issue after the changes to role mapping?

From what I recall, we created v2 of the API which has the right permissions. But, Nebari uses v1, which I don't think was updated.

I think we can close this issue, though. The next step is for Nebari to start using v2.
