### ISSUE TITLE
MAINT - Add new issue templates

### ISSUE THREAD

**Issue by trallard** [conda-incubator/conda-store#585]
@trallard - (Non-blocking comment) Shall we add a new issue template for releases and link to that in the docs here?

_Originally posted by @pavithraes in https://github.com/conda-incubator/conda-store/pull/580#discussion_r1329111984_

**Comment by pavithraes** [comment]
It'll also be nice to have a template for use support questions, since we'll be using the issue tracker as the support forum as well (i.e., in addition to tracking bugs and feature requests).
