### ISSUE TITLE
[BUG] - Ability to downgrade conda-store

### ISSUE THREAD

**Issue by kcpevey** [conda-incubator/conda-store#590]
### Describe the bug

We upgraded conda-store/conda-store-ui to 2023.9.1 (its not clear if all the packages were updated yet). Then after seeing some of the issues, we decided to downgrade back to the previous version. However, the downgrade failed with. 

We suspect that the upgrade resulted in a db change or something because it’s complaining about alembic.

This needs investigation since there was some confusion on whether or not all the releases for conda-store were out yet and we were pulling `latest` so its unclear what we had. 

### Expected behavior

I expect to be able to downgrade conda-store without destroying the database. 

### How to Reproduce the problem?

Upgrade to codna-store et al 2023.9.2, then downgrade to v0.4.15 - this should fail

**Comment by iameskild** [comment]
After upgrading to version `2023.9.2`, you can't seem to downgrade (to v0.4.x) due to the following error:

```
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
FAILED: Can't locate revision identified by 'b387747ca9b7'
ERROR [alembic.util.messaging] Can't locate revision identified by 'b387747ca9b7'
Traceback (most recent call last):
  File "/opt/conda/envs/conda-store-server/bin/conda-store-server", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/conda/envs/conda-store-server/lib/python3.11/site-packages/traitlets/config/application.py", line 1042, in launch_instance
    app.initialize(argv)
  File "/opt/conda/envs/conda-store-server/lib/python3.11/site-packages/traitlets/config/application.py", line 113, in inner
    return method(app, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/conda-store-server/lib/python3.11/site-packages/conda_store_server/server/app.py", line 173, in initialize
    dbutil.upgrade(self.conda_store.database_url)
  File "/opt/conda/envs/conda-store-server/lib/python3.11/site-packages/conda_store_server/dbutil.py", line 97, in upgrade
    check_call(["alembic", "-c", alembic_ini, "upgrade", revision])
  File "/opt/conda/envs/conda-store-server/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['alembic', '-c', '/tmp/tmpgrt_uzl4/alembic.ini', 'upgrade', 'head']' returned non-zero exit status 255.
Stream closed EOF for dev/nebari-conda-store-server-759b667479-t26px (conda-store-server)
```

**Comment by iameskild** [comment]
Unfortunately, I can't shell into this container as it's in an non-running state; it starts up and immediately fails with the above error. We might need to try and recreate this issue using a local version of conda-store to get that information.

**Comment by trallard** [comment]
Well we can "simulate" this condition locally but  within Nebari we might need to nuke the database.

Is there a backup?

**Comment by trallard** [comment]
@iameskild  following on the above

**Comment by trallard** [comment]
@dcmcand This is another issue I just remembered. 
Since we cannot access the output of `alembic history` at this point I am unsure whether this should be debugged of just go down the nuking route
