### ISSUE TITLE
MAINT - Add package constraints to conda recipe

### ISSUE THREAD

**Issue by nkaretnikov** [conda-incubator/conda-store#596]
### Describe the bug

Add _at least_ this constraint to the [conda package](https://github.com/conda-forge/conda-store-feedstock/blob/main/recipe/meta.yaml): `pydantic < 2.0`.

For repro, see: https://github.com/conda-incubator/conda-store/issues/584. I don't know if the lower bound needs to be specified.

There are other constraints in `conda-store/conda-store-server/environment.yaml`, but I don't have a repro for those. So I suggest to just fix this for pydantic for now.

### Expected behavior

pydantic `1.*` is installed when you install conda-store-server.

### How to Reproduce the problem?

See above.

**Comment by nkaretnikov** [comment]
Important: make sure the repro mentioned above no longer repros when constraints are added.

**Comment by jaimergp** [comment]
This can be addressed with a patch via `conda-forge/conda-forge-repodata-patches-feedstock`.

**Comment by trallard** [comment]
Already contained in the release issue, closing as addressed
