### ISSUE TITLE
META - CLI improvements/redesign

### ISSUE THREAD

**Issue by trallard** [conda-incubator/conda-store#597]
### Feature description

Several issues have already opened regarding CLI error handling, parsing, etc. 

The current CLI uses traitlets, which come with some limitations. It would be nice to revisit the old #248 issue and rethink how the conda-store CLI should behave and whether we want to look at other tools/implementation approaches, such as:

- argparse
- rich
- click

## Related issues

#461 
#594 
#516 

### Value and/or benefit

This would allow us to provide a better user experience, better argument handling and error handling

**Comment by asmeurer** [comment]
FWIW I like argparse than click. It has more polish than click for various corner cases in terms of how it parses the actual arguments which makes for a better user interface.

**Comment by dharhas** [comment]
I assume this intersects with configuration as well. My understanding is that we configure conda-store in Nebari via traitlets as well.

**Comment by trallard** [comment]
That is correct

**Comment by costrouc** [comment]
This is low priority but @nkaretnikov has not progress on this. This needs discussion from design side as well.
