### ISSUE TITLE
[BUG] - Review and improve docker images

### ISSUE THREAD

**Issue by pavithraes** [conda-incubator/conda-store#599]
### Describe the bug

Currently, we have 2 Dockerfiles used to build images:
- [conda-store](https://github.com/conda-incubator/conda-store/blob/main/conda-store/Dockerfile), which does an editable install:
https://github.com/conda-incubator/conda-store/blob/64552a28e649d7305ec971332cfb739286769ec9/conda-store/Dockerfile#L22-L23
❗️this is also the file used during releases which should not be the case
- [conda-store-server](https://github.com/conda-incubator/conda-store/blob/main/conda-store-server/Dockerfile), which installs a local directory:
https://github.com/conda-incubator/conda-store/blob/64552a28e649d7305ec971332cfb739286769ec9/conda-store-server/Dockerfile#L49-L51

These are used by the `docker-compose.yaml` in:
- the [root dir](https://github.com/conda-incubator/conda-store/blob/main/docker-compose.yaml), used by developers for local development
- the examples dir intended for end-users --❗️we should use released versions from PyPI or conda-forge here, or refer to the docker images built on releases
  - [`docker/docker-compose.yaml`](https://github.com/conda-incubator/conda-store/blob/main/examples/docker/docker-compose.yaml) - ❗️this file also has defined `redis` twice, which causes errors while building
  - [`docker-without-nfs/docker-compose.yaml`](https://github.com/conda-incubator/conda-store/blob/main/examples/docker-without-nfs/docker-compose.yaml)

☝🏽Additionally, the port number 5000, where the UI is deployed for development does not work reliably on MacOS. We need to pick default ports that work on all platforms.

### Expected behavior

We need to have separate images for building dev and stable versions of conda-store. The releases should use to stable versions.

### Anything else?

xref: #589, #566

**Comment by pavithraes** [comment]
I think we can use the [`docker-compose.yaml` in conda-store-ui](https://github.com/conda-incubator/conda-store-ui/blob/main/docker-compose.yml), as is and as a ref, for the examples directory.

**Comment by kcpevey** [comment]
@dcmcand it looks like the review is complete and all of the issues have been opened as separate issues. Can we close this in favor or the individual issues?

**Comment by dcmcand** [comment]
Yes @kcpevey, we can close this one.  The only outstanding issue is #618. That should be a pretty easy one.
