### ISSUE TITLE
[BUG] - Active build button missing 

### ISSUE THREAD

**Issue by iameskild** [conda-incubator/conda-store#601]
### Describe the bug

When there are multiple builds, you there is no button to active the build you want. 

This build is available but there is no "activate" button.

<img width="775" alt="Screenshot 2023-09-28 at 15 08 00" src="https://github.com/conda-incubator/conda-store/assets/42120229/782ffc76-246e-4ddd-a41e-7b81f417540f">

### Expected behavior

I can't find a screenshot of it and it's not mentioned in the docs but I believe there was a button to activate the environment.

### How to Reproduce the problem?

Create multiple builds of the same environment, and then try to active the one that is not currently active.

### Versions and dependencies used.

conda-store - `203.9.2`

**Comment by trallard** [comment]
This is not a bug but activation and edit workflows were separated in https://github.com/conda-incubator/conda-store-ui/pull/271

**Comment by iameskild** [comment]
Got it. Sounds like this change just needs to be documented 👍

**Comment by trallard** [comment]
Everything in conda store needs documenting
