### ISSUE TITLE
CI - Run tests on Windows

### ISSUE THREAD

**Issue by nkaretnikov** [conda-incubator/conda-store#603]
### Context

Filing a separate issue, so this doesn't get lost in the comments.
Our tests only use Ubuntu now.

### Value and/or benefit

Windows is tested automatically.

**Comment by nkaretnikov** [comment]
Related:
- https://github.com/conda-incubator/conda-store/issues/588
- https://github.com/conda-incubator/conda-store/issues/507 
- https://github.com/conda-incubator/conda-store/issues/71

**Comment by nkaretnikov** [comment]
From `.github/workflows/tests.yaml`:
```
# cannot run on windows due to needing fake-chroot for conda-docker
```

**Comment by asmeurer** [comment]
This will be added to #559
