### ISSUE TITLE
CI - Run tests on macOS

### ISSUE THREAD

**Issue by nkaretnikov** [conda-incubator/conda-store#604]
### Context

Filing a separate issue, so this doesn't get lost in the comments.
Our tests only use Ubuntu now.

### Value and/or benefit

macOS is tested automatically.

**Comment by nkaretnikov** [comment]
Related:
- https://github.com/conda-incubator/conda-store/issues/507
- https://github.com/conda-incubator/conda-store/issues/71
- https://github.com/conda-incubator/conda-store/issues/562
  > From today's meeting, we should have a helpful error message here. Also, as a sidenote, we should change the default port to something other than 5000 (because 5000 doesn't work on Mac machines).

**Comment by nkaretnikov** [comment]
From `.github/workflows/tests.yaml`:

```
# osx takes forever to get a scheduled job
```

**Comment by nkaretnikov** [comment]
Note: du calculation is wrong on macOS, see here https://github.com/conda-incubator/conda-store/pull/559/files#r1342122743

**Comment by asmeurer** [comment]
Already in progress at #550
