### ISSUE TITLE
[BUG] - without --standalone, server runs but fails to build env

### ISSUE THREAD

**Issue by nkaretnikov** [conda-incubator/conda-store#605]
### Describe the bug

When starting the server without the `--standalone` parameter, this error appears when trying to build an env.
No user-friendly error is raised on server start up, which is confusing.

```
'NoneType' object has no attribute 'disk_free'
```

Log for Windows below, but it repros the same on Linux.

### Expected behavior

A user-friendly error is raised on server start-up

### How to Reproduce the problem?

<img width="1696" alt="Screen Shot 2023-10-01 at 19 10 29" src="https://github.com/conda-incubator/conda-store/assets/10469885/086c501d-b5b0-43f4-aa57-bd08fdb45f05">

Env:
```
channels:
  - conda-forge
dependencies:
  - python
  - pip:
    - nothing
  - ipykernel
  # tests
  - pytest

  - requests  # for app

# other fields
description: ''
name: test-env    # required
prefix: null
variables: null
```

### Versions and dependencies used.

On Linux, this was tested on  a8d352443795a6660e0344c93fd43de24c171ebe, which is on top of 432eaa11ef349fdb848215113caea22b09a23a32

**Comment by asmeurer** [comment]
Actually I'm impressed you got this traceback on Windows. For me, the error is hidden on Windows and I was only able to see it after some debugging.

**Comment by nkaretnikov** [comment]
> Actually I'm impressed you got this traceback on Windows. For me, the error is hidden on Windows and I was only able to see it after some debugging.

What do you mean by "hidden"? Yes, for me it printed to the terminal where all server logs are printed.

Perhaps it's related to which terminal you use. I use Windows Terminal that ships with Win11, which is Powershell, I think.
