### ISSUE TITLE
[ENH] - Add large+realistic environments to CI tests

### ISSUE THREAD

**Issue by pavithraes** [conda-incubator/conda-store#612]
### Feature description

We currently have some short integration tests, we can add some realists and large environments to the test suite.

Originally proposed by @dharhas 

### Value and/or benefit

These will help catch issues early that we currently catch only after releases and/or testing with Nebari (the primary conda-store user).

### Anything else?

We have some environments created for other projects. We can use these directly or as reference.

_No response_

**Comment by trallard** [comment]
@peytondmurray I cannot remember if this was tackled already, can you confirm?

**Comment by peytondmurray** [comment]
There's a complicated environment that got merged in #812, but it's currently only used in `conda_store_server/tests/user_journeys/test_user_journeys.py::test_cancel_build`. Maybe it makes sense to use this in some of our other user journey tests?

**Comment by trallard** [comment]
We could perhaps reuse this. Let's discuss potential pathways.

**Comment by peytondmurray** [comment]
Let's close this for now, if we need more complex environments in the future please open an issue.
