### ISSUE TITLE
[BUG] - port 5000 is a problem on MacOS

### ISSUE THREAD

**Issue by dcmcand** [conda-incubator/conda-store#618]
### Describe the bug

Split from #599 
References from #566

MacOS uses port 5000 for airplay with new versions of MacOS. This means that running conda-store-server on port 5000 does not work for many users.

### Expected behavior

Conda store server works on the default port for all major OS's

### How to Reproduce the problem?

Try to run conda-store-server on a recent MacOS machine. 

### Output

It will fail with a message saying that port 5000 is already in use.

**Comment by trallard** [comment]
Related https://github.com/conda-incubator/conda-store/issues/562

**Comment by dcmcand** [comment]
Is there any reason not to use 8080 instead of 5000? 8080 is not a privileged port, is not used by OS processes and is officially an alternative port for http.
