### ISSUE TITLE
Refactor workflows to use composite action for docker build and push

### ISSUE THREAD

**Issue by dcmcand** [conda-incubator/conda-store#629]
### Context

Currently there is duplication on the ci/cd pipeline for building and pushing docker images. Refactor the pipeline to either use a reusable workflow or a composite action to reduce the duplication.

### Value and/or benefit

Reduces complexity and gives you a single place to update the pipeline.

### Anything else?

https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

**Comment by costrouc** [comment]
This is a nice to have and not high priority. @dcmcand doesn't have anything to report on this issue.

**Comment by nkaretnikov** [comment]
@dcmcand no progress on this so far, right? Just checking because the milestone is due by Dec 31.

**Comment by nkaretnikov** [comment]
@dcmcand I've discovered this by looking at milestone issues. What's the status here? I suspect it was marked as "Ready" by mistake?
