### ISSUE TITLE
[BUG] - Make docker-compose and playwright optional on ARM64

### ISSUE THREAD

**Issue by nkaretnikov** [conda-incubator/conda-store#630]
### Describe the bug

```
conda-store-server % conda env create -f environment-macos-dev.yaml
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
Channels:
 - conda-forge
 - Microsoft
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - playwright

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/Microsoft/osx-arm64
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/r/osx-arm64

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

### Expected behavior

All packages install.

### How to Reproduce the problem?

See above.

### Versions and dependencies used.

01ef8962f48bbfa21197301619511aa0857c8e76

**Comment by nkaretnikov** [comment]
Note: installs fine on Intel x86_64, but Intel macs are deprecated. We need to test on m1, m2. GitHub/CircleCI have ARM64 runners.

**Comment by nkaretnikov** [comment]
Could it be the case that our mac CI job only runs on x86_64 macs?

This post mentions m1 machines, are these selected automatically when you select a large runner? https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/

Here's pricing (see "M1" there): https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions I think these are only available to paying customers.

**Comment by nkaretnikov** [comment]
Need to make these optional on aarch64/ARM64. These fail on this architecture on Linux as well.

```
ResolvePackageNotFound:
  - playwright
  - docker-compose
```

**Comment by soapy1** [comment]
Closing as this is an old issue - there is no longer a `environment-macos-dev.yaml` file.
