### ISSUE TITLE
[ENH] - Use rattler and pixi instead of standard conda tooling

### ISSUE THREAD

**Issue by nkaretnikov** [conda-incubator/conda-store#643]
### Feature description

See this talk from PackagingCon 2023:
https://cfp.packaging-con.org/2023/talk/V8R3D7/
How we used Rust to modernize the conda ecosystem
Bas Zalmstra

### Value and/or benefit

Based on my conversation with Bas after the conference:
- rattler is faster than mamba due to optimizations they were able to do
- should be compatible in terms of features (that we use)
- pixi doesn't write to system files (no changes to .bashrc or similar necessary - can be annoying to users or on CI)
- written in Rust, so easy to modify compared to C solver libs (I love Rust), which is how they managed to optimize it better
- rattler has python bindings
- new tooling, without legacy code
- prefix people are friendly and open to patches if necessary.

### Anything else?

This is just an idea to explore, not an immediate call to action.

**Comment by nkaretnikov** [comment]
Alternatively, if we cannot integrate this tooling right away, we just need to see what it does differently and port these ideas to conda-store.

**Comment by jaimergp** [comment]
Noting here that `pixi` (iow `rattler`) is going to integrate `uv` as the PyPI resolver (instead of `resolvo`). Maybe the safest way to benefit from this is to wait for this integration to happen, and/or enable conda-lock to use `uv` instead of `poetry`.

**Comment by peytondmurray** [comment]
Closing this in favor of #929, where effort will begin on a pluggable backend that enables this.
