### ISSUE TITLE
[ENH] - Use wolfi for docker containers

### ISSUE THREAD

**Issue by nkaretnikov** [conda-incubator/conda-store#644]
### Feature description

See this talk from PackagingCon 2023:
https://cfp.packaging-con.org/2023/talk/TWAZYN/
Wolfi: Building a New Linux (Un)distro
Adrian Mouat

### Value and/or benefit

- wolfi is a small distribution for Docker containers
- like Alpine, but based on glibc, which solves compat problems that people have with musl
- small
- reproducible builds
- built with SBOMs and automatic vuln scanning in mind (is my container image vulnerable?)
- has commercial support by chainguard, but wolfi is a community project that you can just use
- http://wolfi.dev/

### Anything else?

Just an idea to explore, not an immediate call to action.

**Comment by rigzba21** [comment]
Linking https://github.com/conda-incubator/conda-store/issues/297 here.

**Comment by rigzba21** [comment]
Wolfi OS does have a `conda` package here: https://github.com/wolfi-dev/os/blob/main/conda.yaml.

**Comment by peytondmurray** [comment]
Thank you for the suggestion. For now we're going to stick with the most basic and maintainable linux distros for our containers. Let's revisit in the future if we see a need for this.
