### ISSUE TITLE
[ENH] - Consider using OS-specific standards for `conda-store` data

### ISSUE THREAD

**Issue by jaimergp** [conda-incubator/conda-store#648]
### Feature description

As part of #513, it was suggested to use `~/.conda-store` as the default data directory. This was implemented successfully in https://github.com/conda-incubator/conda-store/pull/639.

I am suggesting we stick to well defined standards for this kind of decisions, instead of polluting the home directory with one more dot-folder. Namely:

- On Linux, follow [XDG Base Directory Specification
](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)
- On macOS, it seems that CLI apps still follow XDG standards as Linux. GUI stuff drops things in `~/Library`. See this [SO thread](https://stackoverflow.com/questions/3373948/equivalents-of-xdg-config-home-and-xdg-data-home-on-mac-os-x).
- On Windows, we should probably use [`%LOCALAPPDATA%`](http://msdn.microsoft.com/en-us/library/windows/desktop/dd378457%28v=vs.85%29.aspx) (i.e. non-roaming).

### Value and/or benefit

Following well established standards in each Operating System allow us to be better citizens, and navigate better known spaces (e.g. permissions, lack of user profiles in some Windows installations).

A nice side effect, and one of the reasons these standards exist, is to avoid polluting the user profile with dot-directories.

### Anything else?

Comes from https://github.com/conda-incubator/conda-store/pull/639#issuecomment-1787555517

**Comment by nkaretnikov** [comment]
ArchWiki list, with links to various issues: https://wiki.archlinux.org/title/XDG_Base_Directory_support

**Comment by costrouc** [comment]
Yeah totally agree we should use system defaults

**Comment by jaimergp** [comment]
`conda` is going to [switch](https://github.com/conda/conda/pull/13307) to `platformdirs` (instead of the vendored `appdirs`), which seems to abstract away all the complicated business:

https://platformdirs.readthedocs.io/en/latest/index.html

**Comment by nkaretnikov** [comment]
Status update: not working on this until other issues in the milestone are resolved.
