### ISSUE TITLE
[BUG] - new UI is gray when running in standalone mode

### ISSUE THREAD

**Issue by nkaretnikov** [conda-incubator/conda-store#651]
### Describe the bug

The home page doesn't have green UI elements, like when running in Docker.

To repro:
```
# server
python -m conda_store_server.server --standalone --config config.py

# ui
yarn run start 
```

config.py:
```py
# This MUST start with `/`
c.CondaStoreServer.url_prefix = "/conda-store"
```

### Expected behavior

Green elements are shown, like with Docker.

### How to Reproduce the problem?

See above.

### Versions and dependencies used.

server: 0760fa2b386bc207936df89f52b4df83f61e8af8
ui: cf6a34f8b9a44f6c10c9466ac423852373d52168, base: b4a5b46732f3441084fff4ff5537d494f0f3f09e

**Comment by nkaretnikov** [comment]
<img width="997" alt="Screen Shot 2023-11-03 at 18 31 53" src="https://github.com/conda-incubator/conda-store/assets/10469885/9c98bdf3-954b-493e-9bcf-57bc6206bb9d">

The Log out button and the logo at the bottom should be green.

**Comment by nkaretnikov** [comment]
It's possible I'm just starting the UI incorrectly (due to not setting up some config properly). I filed an issue so I don't forget about this. In any case, it seems like it should pick up the themed green UI by default.

**Comment by steff456** [comment]
Hi!!

Currently the UI supports two themes, grayscale and green. You are able to change it by setting this environment variable,

```
REACT_APP_STYLE_TYPE=grayscale #gray UI
REACT_APP_STYLE_TYPE=green-accent #green UI
```

**Comment by nkaretnikov** [comment]
Fixed in https://github.com/conda-incubator/conda-store-ui/pull/327.
