### ISSUE TITLE
[ENH] - Teach conda-store how to generate `constructor` artifacts

### ISSUE THREAD

**Issue by jaimergp** [conda-incubator/conda-store#657]
### Feature description

conda-store is able to generate several artifacts from an existing environment:

- Docker environment
- Lockfile
- conda-pack archive

`constructor` is able to generate more formats, like self-contained installer scripts for Unix, or native macOS or Windows step-by-step GUI installers.

This would need extra configuration fields that `constructor` expects.

### Value and/or benefit

More diversity of exported formats, which would come handy for application distribution, opening the doors for new personas in conda-store (e.g. product manager that needs to generate installers for the latest release of their app).

### Anything else?

This is part of the STF funding, deliverable 4.

It will also allow to use a hypothetically unified interface for all types of "environment artifacts" (e.g. see https://github.com/conda/conda-pack/issues/294), so we can simplify our integrations.

**Comment by nkaretnikov** [comment]
Related: https://github.com/conda/constructor/issues/730
