### ISSUE TITLE
[ENH] - Safer `pip` integrations

### ISSUE THREAD

**Issue by jaimergp** [conda-incubator/conda-store#661]
### Feature description

Right now, we have some kind of "extra" checks around `pip` requirements via the `Specification` schema, but other than that, we just delegate to `conda env`.

The idea here is to handle `pip` packages a bit more safely, as described in [this draft](https://gist.github.com/jaimergp/56c1a5f6c18d4905c578e69bac079fbb).

Then we would modify [this block](https://github.com/conda-incubator/conda-store/blob/4db34b72f7b095b41ece7473b20a6016662031a7/conda-store-server/conda_store_server/build.py#L130-L142) so we only pass the `conda` deps to `conda env`, but we handle `pip` packages separately, as described in the draft. 

Something like:

```python
conda_pkgs, pip_pkgs = pkgs_from_environment_yml()
for pip_pkg in pip_pkgs:
   conda_deps, pip_deps = grayskull(pip_pkg, recursive=True)
   conda_pkgs.extend(conda_deps)
   pip_pkgs.extend(pip_deps)
conda_files = files_from_conda_solve(conda_pkgs)
pip_files = files_from_pip_install(pip_pkgs)
if pip_files.intersect(conda_files):
  # warn, or error
if not shared_objects(pip_files):
  # warn, or error
... # maybe other checks
conda_create(conda_pkgs)
pip_install(pip_pkgs)
```

### Value and/or benefit

Safe pip integrations with reduced risk of clobbering and ABI incompatibilities.

### Anything else?

This might start as a separate module, or maybe as a different repository.

**Comment by jaimergp** [comment]
CLI prototype at https://github.com/jaimergp/conda-pip

You can try it out in your `base` environment with:

```
$ conda install -nbase grayskull pip
$ pip install https://github.com/jaimergp/conda-pip/archive/main.tar.gz
```

And then run commands like:

```bash
$ conda pip install scipy  # should tell you it will get it from conda
$ conda pip install ragna
Analyzing dependencies: done
conda will install:
 - aiofiles
 - emoji
 - fastapi
 - huey
 - httpx
 - importlib-metadata[version='>=4.6']
 - packaging
 - panel[version='>=1.3,<1.4']
 - pydantic[version='>=2']
 - pydantic-core
 - pydantic-settings[version='>=2']
 - pyjwt
 - python-multipart
 - redis-py
 - questionary
 - rich
 - sqlalchemy[version='>=2']
 - tomlkit
 - typer
 - uvicorn
pip will install:
 - ragna==0.1.1
Proceed ([y]/n)? 
# will run 'conda install' and 'pip install --no-deps', respectively
```

**Comment by dharhas** [comment]
This is very promising. I like the direction. One longer term issue will be related to the UI. Whether we make pip packages easier to select and how we communicate what has been done under the hood. i.e. should we optionally spit out a new env.yaml with the packages moved to the conda section.

**Comment by trallard** [comment]
Perhaps we will need a new yaml for visibility.
If that were the case we should probably add some auto generated header too.

**Comment by jaimergp** [comment]
See `jaimergp/conda-pip`. Still not ready for integration in `conda-store`, but hoping to make more progress during December.

**Comment by jaimergp** [comment]
Current status:

* I identified some issues with the `grayskull` based solver and implemented another based on `pip`. Planning to [add another based on `uv`](https://github.com/jaimergp/conda-pip/issues/14).
* I also added some very basic tests to ensure some things do work. Still, this tool would benefit from a lot of testing on real case scenarios.
* I also opened https://github.com/conda/conda/issues/13833 to discuss how to better [integrate this tool with `conda env](https://github.com/jaimergp/conda-pip/issues/16)` so the safe `pip` is used instead of the regular `pip` when installing `environment.yml` files with `- pip:` sections.

I guess some [documentation](https://github.com/jaimergp/conda-pip/issues/17) could be beneficial here, which I haven't added yet. I plan to do so after getting some consensus on the name of the project ([see related issue](https://github.com/jaimergp/conda-pip/issues/15)), but I can do it already if someone on the team wants to test this locally?

**Comment by jaimergp** [comment]
Renamed to `conda-pypi` (https://github.com/jaimergp/conda-pypi/pull/18) and added documentation (https://github.com/jaimergp/conda-pypi/pull/19).

Useful reads (this is not yet on GH Pages):

- [Quickstart](https://github.com/jaimergp/conda-pypi/blob/main/docs/quickstart.md)
- [Motivation](https://github.com/jaimergp/conda-pypi/blob/main/docs/why.md)
- [Contribution guidelines](https://github.com/jaimergp/conda-pypi/blob/main/CONTRIBUTING.md)

**Comment by trallard** [comment]
Will close this as it is completed for the purpose of Challenges. And the project has now been moved to https://github.com/conda-incubator/conda-pypi

**Comment by dharhas** [comment]
Is there another issue tracking moving towards using conda-pypi in conda-store to enable safer pip integration?

**Comment by jaimergp** [comment]
Opened https://github.com/conda-incubator/conda-store/issues/845
