### ISSUE TITLE
[ENH] - Add ability to create environment from lockfile

### ISSUE THREAD

**Issue by kcpevey** [conda-incubator/conda-store#676]
### Feature description

The only(ish) way to guarantee a fully reproduced environment is through lockfiles. We produce them, but that's only truly useful if we can USE them. 

I propose that conda-store add the ability to create environments from lockfiles. 

### Value and/or benefit

Reproducibility!

**Comment by jaimergp** [comment]
IIRC, we use `conda-lock` to resolve and lock an environment.yml into a conda-lock.yml file. Then `conda-lock install` takes the lockfile and creates the environment. Naively speaking, "all this needs" (famous last words) is a dropdown to choose the kind of input conda-lock is expecting (environment.yml, conda-lock.yml straight, or something else). Maybe a couple refactors in the database if the "environment.yml is the only input" assumption is too hardcoded.

**Comment by kcpevey** [comment]
This will need a follow-up issue on the UI repo to enable this for end users.
