### ISSUE TITLE
How to prioritize a celery task chain to complete before starting new builds

### ISSUE THREAD

**Issue by ClaytonAstrom** [conda-incubator/conda-store#683]
### Context

Something that isn't clear in the administration is the following situation -

* Queue a series of 10 builds
* Build 1 is picked up with CONDA_PACK enabled
* Build 2 starts, Build 3 starts, ..., Build 10 starts
* Build 1 CONDA_PACK starts

Why is the rest of the chain put behind all the other builds?  Would the `worker_prefetch_limit` help?

### Value and/or benefit

It's difficult to have a high volume queue in flight

**Comment by ClaytonAstrom** [comment]
Some clarification - this is true even for a single worker node

**Comment by ClaytonAstrom** [comment]
Hm, this may be something that was resolved with #473 , my mistake!

**Comment by pavithraes** [comment]
Thanks for opening this issue and following up! 🌻
