### ISSUE TITLE
[BUG] - Unable to build environment using Conda-Store standalone 

### ISSUE THREAD

**Issue by aditipate** [conda-incubator/conda-store#729]
### Describe the bug

Hi, I am a new user of Conda-Store and was experiencing issues using the conda-store standalone, specifically when attempting to build a simple environment using the UI. I followed the documentation instructions/tutorial as listed here: https://conda.store/conda-store/introduction. 

My Steps: 
1. First I Installed conda-store and conda-store-server 
```pip install conda-store conda-store-server```
2. Next I started a standalone local instance 
```conda-store-server  --standalone```
3. I used the UI by accessing it at localhost:8080

I then followed the instructions in the UI tutoritals: https://conda.store/conda-store-ui/tutorials/
1. I clicked on login and created a user with password `password`
2. I then attempted to create a simple, new environment in the "default" namespace using the instructions from the tutorial but this did not work. 
Here's where I ran into some issues. The environment does not seem to build and there is no error message besides a a red rectangle indicating an error or the environment wasn't built (can't hover over it). I am also unable to access the user page when I click on user. 

Any help would be appreciated. I have also provided screenshots. The Docker installation is also not working for me. 

Screenshots:
<img width="1792" alt="Screenshot 2024-01-10 at 1 19 47 PM" src="https://github.com/conda-incubator/conda-store/assets/65534760/2525f956-1646-4b6b-b189-6ec3eb4e0aae">
<img width="1788" alt="Screenshot 2024-01-10 at 1 19 55 PM" src="https://github.com/conda-incubator/conda-store/assets/65534760/6a7e97ca-4934-4aca-9c22-18aeceb350e8">

### Expected behavior

- I expect the environment build to show its status, as shown in the standalone/UI tutorial.

### How to Reproduce the problem?

I have provided the steps I took in the bug issue description. Here are the steps listed again: 

I followed the documentation instructions/tutorial as listed here: https://conda.store/conda-store/introduction. 

My Steps: 
1. First I Installed conda-store and conda-store-server 
```pip install conda-store conda-store-server```
2. Next I started a standalone local instance 
```conda-store-server  --standalone```
3. I used the UI by accessing it at localhost:8080

I then followed the instructions in the UI tutoritals: https://conda.store/conda-store-ui/tutorials/
1. I clicked on login and created a user with password `password`
2. I then attempted to create a simple, new environment in the "default" namespace using the instructions from the tutorial but this did not work. 

Here's the YAML file I used:
```yaml
name: python-data-science-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - ipywidgets=7.7.0
  - pandas=1.5.3
  - numpy=1.24.2
  - biopython=1.78
  - scikit-learn=1.2.2
   ```

**Comment by trallard** [comment]
Thanks for flagging this up and providing all the reproduction steps @aditipate 

I will have a look at this issue and report back with any findings. 
Just so that I have all the information - what version of conda-store and conda-store-ui are you using?

**Comment by pavithraes** [comment]
@aditipate Thanks for opening a thorough issue with all the steps you took. :)

Using `conda_store_server = 2023.10.1` (which is the current latest version), running in standalone mode in macOS, I'm able to build an environment using your YAML spec:

![Screenshot 2024-01-16 at 9 35 02 PM](https://github.com/conda-incubator/conda-store/assets/33131404/cff35818-3218-4c70-afd6-c30d976d29e4)

>Just so that I have all the information - what version of conda-store and conda-store-ui are you using?

Additionally, could you please share which your **operating system** (linux/windows/macos) you're on and if you have [**`conda` setup**](https://docs.conda.io/projects/conda/en/stable/user-guide/install/index.html) on your computer?

Also, note that standalone is in early development and the next release (which will happen quite soon) should have better support for this. :)

**Comment by pavithraes** [comment]
@aditipate Hi! We now have a new version of conda-store-server: [2024.1.1](https://github.com/conda-incubator/conda-store/releases/tag/2024.1.1). Please let us know if the issue still persists, and share the additional information if it does. :)

**Comment by pavithraes** [comment]
I'll go ahead and close this as unreproducible, please feel free to re-open if needed!
