### ISSUE TITLE
[ENH] - Loosen requirements on environment name

### ISSUE THREAD

**Issue by kcpevey** [conda-incubator/conda-store#749]
### Feature description

There are two interrelated issues around the environment name specification via the UI. 

1. Spaces in the name are invalid.
2. The error that users see when adding spaces to the name is not helpful.

To reproduce - Create any new environment with a space in the name. 

This is the result:
![image](https://github.com/conda-incubator/conda-store-ui/assets/15659110/0d5b6067-1fbb-4d2b-a6eb-1d05f4cfaa2b)

### Value and/or benefit

I hit this error after copying in a huge yaml file. I spent time trying to figure out which package name was not properly named. I finally realized it was the environment name that was invalid. 

It feels like the proper solution would be to find/replace spaces with underscores. At the very least, the error message needs improvement. Telling people which section of the env spec or giving them the exact line that failed would be super helpful.

**Comment by trallard** [comment]
It is recommended that `conda` envs do not include spaces in their names, even some symbols are suggested against across OS's.

So we will not be implementing this change as this would effectively go against `conda` best practices/recommendations
