### ISSUE TITLE
Reference - Update REST API docs

### ISSUE THREAD

**Issue by pavithraes** [conda-incubator/conda-store#754]
Create a REST API reference at: https://conda.store/conda-store/references/api

Tasks:
- Integrate a plugin for openapi <> docusaurus (blocked - currently, the plugin in not compatible with docusaurus v3)
- Create a GH action to generate openapi.json regularly for keeping the reference up-to-date

**Comment by peytondmurray** [comment]
We have openapi docs that work at the moment; let's revisit later if folks want to have more robust REST api docs.
