### ISSUE TITLE
DOC - Adjust snapshots in docs

### ISSUE THREAD

**Issue by trallard** [conda-incubator/conda-store#756]
Because we no longer have the "red boxes" to direct your attention to a portion of the screen, I decided to crop the images to only include the region of interest. If you check the netlify docs, the image sizes are now inappropriate. I recommend that this can be merged and that the auto generated PR on the other side be worked on to resize the images in the docs.

_Originally posted by @kcpevey in https://github.com/conda-incubator/conda-store-ui/issues/346#issuecomment-1885690171_

**Comment by pavithraes** [comment]
Blocked on `https://github.com/conda-incubator/conda-store-ui/pull/346#issuecomment-1885690171`
