### ISSUE TITLE
Document support for `variables` in environment spec

### ISSUE THREAD

**Issue by pavithraes** [conda-incubator/conda-store#759]
### Context

In https://github.com/conda-incubator/conda-store-ui/pull/354, we add support for passing environment variables in the `conda-store-ui` through the YAML editor.
This allows users to create envs for GPU-powerd workflows, by adding the `CONDA_OVERRIDE_CUDA`.
This needs to be documented in https://conda.store/conda-store-ui/tutorials/create-envs#graphical-interface, with a new 3rd level heading after the pip section.

### Value and/or benefit

Documenting available features for conda-store users.

**Comment by nkaretnikov** [comment]
Status update: the respective documenation PR is in review, but it's blocked until https://github.com/conda-incubator/conda-store-ui/pull/354 lands.
