### ISSUE TITLE
[DOC] Update documentation website theme

### ISSUE THREAD

**Issue by pavithraes** [conda-incubator/conda-store#764]
### Context

The documentation currently uses very basic conda-store brand colors, but these need to be updated esp for dark mode.

### Value and/or benefit

Consistent and more polished website.

**Comment by smeragoel** [comment]
Update: I've worked on a color system for this, and I'm currently working with @pavithraes to iron out a few kinks and to understand what variables and colors are being used in the theme

**Comment by smeragoel** [comment]
I discussed with @pavithraes that I'd need to see some previews before I can finalise the colours, so this is a starting point to see how the colours look and I'll tweak them accordingly

```
:root {
  /* Light */
  /* colors */
  ----ifm-color-primary: #298642;
  ----ifm-color-primary-dark: #206532;
  ----ifm-color-primary-darker: #144321;
  ----ifm-color-primary-darkest: #0a2210;
  ----ifm-color-primary-light: #5cb975;
  ----ifm-color-primary-lighter: #85cb97;
  ----ifm-color-primary-lightest: #d6eedc;
  /* Dark */
  /* colors */
  ----ifm-color-primary: #5cb975;
  ----ifm-color-primary-dark: #85cb97;
  ----ifm-color-primary-darker: #addcba;
  ----ifm-color-primary-darkest: #d6eedc;
  ----ifm-color-primary-light: #298642;
  ----ifm-color-primary-lighter: #206532;
  ----ifm-color-primary-lightest: #144321;
}
```
