### ISSUE TITLE
Investigate SQLAlchemy deprecation notes

### ISSUE THREAD

**Issue by trallard** [conda-incubator/conda-store#771]
### Describe the bug

As I was reviewing the fails for https://github.com/conda-incubator/conda-store/actions/runs/8099746158/job/22136222668?pr=765 I realised there are a few deprecation warnings there.		realized

### Expected behavior

We should not use deprecated features or/and pinning SQLAlchemy while we fix those.		

### How to Reproduce the problem?

Run conda-store unit tests; then the warning should pop up

**Comment by peytondmurray** [comment]
Revisted these in a recent unit test run and couldn't find any sqlalchemy related deprecation warnings. Please reopen if the issue persistss.
