### ISSUE TITLE
Synthesise UX results and publish them

### ISSUE THREAD

**Issue by pavithraes** [conda-incubator/conda-store#817]

**Comment by pavithraes** [comment]
Smera is working on the report right now. We'll also need to include this in the project documentation, which I can help with. :)

**Comment by smeragoel** [comment]
The wip report is here: [[DRAFT] User Testing Results](https://docs.google.com/document/d/1ZbhSr6TY34LYkDoW3FKPdmVRK-hf-asl-sZ3YOlXt9w/edit?usp=sharing)

Another important component is the Figjam board where I have consolidated the notes from the interviews, and made an affinity diagram to guide the report: [User Research Data](https://www.figma.com/file/SJqCXfRuwHMscGFGp0G3IU/User-Research-Data?type=whiteboard&node-id=0%3A1&t=3bCOYzzHD0zOp9Hf-1)
