### ISSUE TITLE
[BUG] - Home menu does not turns into green when on it like other

### ISSUE THREAD

**Issue by nakul-py** [conda-incubator/conda-store#894]
### Describe the bug

when new user comes to the website he/she gets confused that which page he/she is on i.e the home menu does not get turn into green and show any sign of that the user on home page .

https://github.com/user-attachments/assets/35876933-1ada-4651-b7f8-05048e0d952c

### Expected behavior

the home menu is getting green when the user click on and when user present on that home page.

### How to Reproduce the problem?

- Click on the  [conda.store](https://conda.store/)

**Comment by peytondmurray** [comment]
Thanks for filing this issue! We appreciate the feedback, but sadly this isn't something we'll fix - this is an upstream docusaurus style choice.
