### ISSUE TITLE
Valid sub-routes for the UI app result in 404

### ISSUE THREAD

**Issue by gabalafou** [conda-incubator/conda-store#899]
Should we redirect all unknown routes to the React (UI) app?

When a user goes directly to a React app-defined sub-route (by sub-route I mean any route that is not the root route, "/"), such as "/:namespace/new-environment", the server will return a 404 instead of returning the [conda-store-ui.html](https://github.com/conda-incubator/conda-store/blob/7d39efa9c708f71875dc48d0dc2800df860b5703/conda-store-server/conda_store_server/_internal/server/templates/conda-store-ui.html) page. 

We should probably **redirect all unknown routes to the React (UI) app**, [conda-store-ui](https://github.com/conda-incubator/conda-store-ui).

That way a user can copy-paste a link like "https://example.com/conda-store/default/new-environment" directly into their browser, as opposed to always having to start from "https://example.com/conda-store". Being able to load non-root routes was the whole point of [introducing URL routing into the front end](https://github.com/conda-incubator/conda-store-ui/pull/389).

**Comment by trallard** [comment]
Does this mean that to get to let's say `namespace/environments` right now the user has to go through `/` then find their way through clicks to `namespace/environments`?

**Comment by gabalafou** [comment]
Yes that's exactly the issue

**Comment by trallard** [comment]
Pffff that sounds awful. So I would be in favour of finding a better way to deal with routes.

**Comment by gabalafou** [comment]
Exactly. The current configuration means defeats the whole point of adding URL routing to the UI app. Part of the argument for getting rid of the tabbed interface was that a user could ctrl- or cmd-click on environments to open them in a new **browser** tab rather than a new Conda Store UI tab. But we can't load the UI at URLs like /:namespace/:environment, then that ability to open environments directly in a new tab (or share them with others via URL) does not work. 

I believe the usual solution here is to create catch-all or fallback route on the server that serves conda-store-ui.html. Right now, I believe the server is configured to serve that file at one and only one URL ("/" by default, or "/conda-store" in other configurations).

**Comment by trallard** [comment]
I assigned you @gabalafou  and @peytondmurray - I would like you two to figure a solution to this.

**Comment by peytondmurray** [comment]
For my understanding, when a user pastes https://example.com/conda-store/foo/bar 

- currently they get a 404
- under the proposed change, we redirect to https://example.com/conda-store, then `window.location` gets parsed to take the user to the `bar` environment in the `foo` namespace

Is that right?

**Comment by gabalafou** [comment]
Yes! Except it's not technically a redirect. It's not a 301. It's a 200 and you serve the conda-store-ui.html template at /foo/bar.

**Comment by peytondmurray** [comment]
Cool, thanks for the clarification - that solution sounds reasonable to me.
