### ISSUE TITLE
[ENH] - Document the ideal way for `conda-store` to be deployed

### ISSUE THREAD

**Issue by peytondmurray** [conda-incubator/conda-store#957]
### Feature description

We need documentation on how to deploy `conda-store` for production environments. Currently we have information about local docker and kubernetes installations, and a bit of information about using NFS, etc. But it would be useful to have full-featured documentation about production installations, including recommendations about instance size, NFS, storage, etc.

### Value and/or benefit

Improved documentation will make `conda-store` more accessible to new users.

**Comment by soapy1** [comment]
related to https://github.com/conda-incubator/conda-store/issues/895 and https://github.com/conda-incubator/conda-store/issues/944

**Comment by soapy1** [comment]
Closing as a duplicate of https://github.com/conda-incubator/conda-store/issues/727
