### ISSUE TITLE
[ENH] - Add attestations for pip packages

### ISSUE THREAD

**Issue by peytondmurray** [conda-incubator/conda-store#962]
### Feature description

We currently publish PYPI packages for `conda-store-server` (and `conda-store`, but that's not as important). Let's add support for [github attestations](https://docs.github.com/en/actions/security-for-github-actions/using-artifact-attestations/using-artifact-attestations-to-establish-provenance-for-builds).

### Value and/or benefit

Provenance will be established for our builds. I don't know if these will be needed by anyone, but it's extremely easy to do with a few extra github action calls and hardly any effort on our side.

**Comment by trallard** [comment]
Just FYI since we are using the pypi-publish action with a trusted publisher, this adds attestations by default already https://github.com/pypa/gh-action-pypi-publish/tree/release/v1/?tab=readme-ov-file#generating-and-uploading-attestations (which are different from the GH attestations)
