### ISSUE TITLE
[MAINT] - Update support for python versions

### ISSUE THREAD

**Issue by peytondmurray** [conda-incubator/conda-store#974]
### Context

Currently we support `python>=3.8`, and functionally speaking `python<3.13` because [`conda` hasn't released support for 3.13 yet](https://github.com/conda/conda/pull/14187). However active support for 3.8 ended 3.5 years ago and there is additionally no longer security support.

Let's find upgrade paths for supporting 3.13 and for dropping old versions.

### Value and/or benefit

Maintaining compatibility with old versions costs developer time, CI time, and prevents us from using new features, like fancy type annotations.

**Comment by soapy1** [comment]
Also sharing https://devguide.python.org/versions/. Python 3.8 EOL was on 2024-10-07

**Comment by trallard** [comment]
We should drop Python 3.8 right away and 3.9, I would say (as this is now only in security mode) https://devguide.python.org/versions/

I would suggest that moving forward, we only support the last four major Python versions (3.10-3.13 in this case, similar to https://scientific-python.org/specs/spec-0000/#implementation).

> Let's find upgrade paths for supporting 3.13 and dropping old versions.

We should already be testing this in our CIs for 3.13. If necessary, let's open a separate issue to track the required updates for 3.13 compatibiity.

**Comment by trallard** [comment]
Closing this issue as completed through #973
